import type { ConceptRelation, ScientificDecisionRecord } from "./types";

export const SCIENTIFIC_DECISIONS: readonly ScientificDecisionRecord[] = Object.freeze([
  { id: "SCI-001", feature: "Evidence-based retrieval scheduler",
    claim: "Retrieval practice distributed over time can improve later retention, while optimal intervals depend on context.",
    evidenceLevel: "LEVEL_A", sources: ["adesope-2017", "kim-2022", "carpenter-pan-butler-2022", "ye-su-cao-2022"],
    supportedMechanism: "Schedule active retrieval after evidence and adapt conservatively to errors and assistance.",
    implementationDecision: "ADAPT", limitations: ["The ELOS learner population has not been experimentally evaluated.", "FSRS is a benchmark, not the complete pedagogical policy."],
    measurementPlan: ["delayed retrieval success", "reviews per retained concept", "missed reviews", "unnecessary reviews"] },
  { id: "SCI-002", feature: "Confidence calibration and assistance dependency",
    claim: "Comparing item confidence with observed performance can identify calibration patterns; confidence alone is not mastery.",
    evidenceLevel: "LEVEL_A", sources: ["gutierrez-de-blume-2022"], supportedMechanism: "Classify confidence-performance pairs using fixed, inspectable rules.",
    implementationDecision: "ADOPT", limitations: ["Self-reported confidence is noisy and may vary across domains."],
    measurementPlan: ["confidence calibration error", "false mastery rate", "support dependence"] },
  { id: "SCI-003", feature: "Adaptive scaffolding and fading",
    claim: "Computer-based scaffolding can support problem-centered STEM learning, but evidence does not justify automatic unrestricted fading.",
    evidenceLevel: "LEVEL_A", sources: ["belland-walker-kim-lefler-2017"], supportedMechanism: "Move one rung at a time and fade only after repeated autonomous success.",
    implementationDecision: "ADAPT", limitations: ["Fading was uncommon in the studies synthesized by the review."],
    measurementPlan: ["assistance reduction", "support dependence", "transfer success"] },
  { id: "SCI-004", feature: "Contrastive interleaving",
    claim: "Interleaving is most defensible when learners must discriminate similar categories, with substantial domain moderation.",
    evidenceLevel: "LEVEL_A", sources: ["brunmair-richter-2019"], supportedMechanism: "Interleave only explicit CONFUSED_WITH relations after an observed error.",
    implementationDecision: "ADAPT", limitations: ["Benefits vary by material and are not established for arbitrary topic mixing."],
    measurementPlan: ["error recurrence", "contrast discrimination success"] },
  { id: "SCI-005", feature: "Self-explanation and transfer",
    claim: "Prompted self-explanation supports learning on average, while successful transfer is distinct and must be measured directly.",
    evidenceLevel: "LEVEL_A", sources: ["bisra-et-al-2018", "pan-rickard-2018"], supportedMechanism: "Score required semantic invariants and keep transfer evidence separate from fluent explanation.",
    implementationDecision: "ADOPT", limitations: ["Effects vary by prompt and domain; response length is not evidence of correctness."],
    measurementPlan: ["self-explanation invariant coverage", "transfer success", "retention after delay"] },
  { id: "SCI-006", feature: "Lightweight concept dependency graph",
    claim: "Explicit prerequisite and confusion relations can make remediation inspectable without inferring a learner trait.",
    evidenceLevel: "LEVEL_C", sources: ["katinskaia-et-al-2023"], supportedMechanism: "Use a small typed relation set with deterministic traversal and provenance.",
    implementationDecision: "ADAPT", limitations: ["Relations require domain review and do not prove causal learning dependencies."],
    measurementPlan: ["prerequisite remediation success", "error recurrence", "path explanation coverage"] },
]);

export const ELOS_CONCEPT_RELATIONS: readonly ConceptRelation[] = Object.freeze([
  { from: "CSV_FIELD_SEPARATOR", to: "CSV_DELIMITER_DIAGNOSIS", type: "PREREQUISITE_OF", provenance: "ELOS Excel CSV Foundations v1" },
  { from: "CSV_DELIMITER_DIAGNOSIS", to: "CSV_DELIMITER_VS_ENCODING", type: "RELATED_TO", provenance: "ELOS Deep Mastery CSV v1" },
  { from: "CSV_DELIMITER_DIAGNOSIS", to: "CSV_ENCODING_DIAGNOSIS", type: "CONFUSED_WITH", provenance: "ELOS observed error taxonomy v1" },
  { from: "TCP", to: "TCP_UDP_CONFUSION", type: "EXAMPLE_OF", provenance: "ELOS networking definition v1" },
  { from: "TCP", to: "UDP", type: "CONFUSED_WITH", provenance: "ELOS networking definition v1" },
  { from: "OSI_MODEL", to: "TCP_IP_MODEL", type: "CONFUSED_WITH", provenance: "ELOS networking definition v1" },
  { from: "AUTHENTICATION", to: "AUTHORIZATION", type: "CONFUSED_WITH", provenance: "ELOS security curriculum v1" },
]);
